name: iOS Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.12'
        channel: 'stable'
        
    - name: Install dependencies
      run: |
        flutter pub get
        
    - name: Install iOS dependencies
      run: |
        cd ios
        pod install
        
    - name: Build iOS app
      run: |
        flutter build ios --release --no-codesign
        
    - name: Archive iOS app
      run: |
        cd ios
        xcodebuild -workspace Runner.xcworkspace \
          -scheme Runner \
          -configuration Release \
          -destination generic/platform=iOS \
          -archivePath Runner.xcarchive \
          archive
          
    - name: Export IPA
      run: |
        cd ios
        xcodebuild -exportArchive \
          -archivePath Runner.xcarchive \
          -exportPath . \
          -exportOptionsPlist ExportOptions.plist
          
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: Runner.ipa
        path: ios/Runner.ipa
